version: '3.7'

services:
  adamweb:
    build: ./backend
    command: uvicorn app.main:app --reload --workers 4 --host 0.0.0.0 --port 8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8010:8000
    # networks:
    #   - adam2
  # db:
  #   image: postgres:12.1-alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER=hello_fastapi
  #     - POSTGRES_PASSWORD=hello_fastapi
  #     - POSTGRES_DB=hello_fastapi_dev
  #   command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
  #   networks:
  #     - postgres
  #   restart: unless-stopped

#   adamdev:
#     image: node:12
#     # build: ./frontend
#     volumes:
#       - ./frontend:/usr/src/service
#     working_dir: /usr/src/service
#     command: yarn start
#     ports:
#       - 3010:3000
#     networks:
#       - adam2
#     restart: unless-stopped

# networks:
#   adam2:
#     driver: bridge
